In [3]:
with open("data.txt", "r", encoding="utf-8") as f:
    text = f.read()

print(text[:500])

data = text.split('\n')
data[:10]


Project Gutenberg's The Adventures of Sherlock Holmes, by Arthur Conan Doyle

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.net


Title: The Adventures of Sherlock Holmes

Author: Arthur Conan Doyle

Release Date: November 29, 2002 [EBook #1661]
Last Updated: May 20, 2019

Language: English

Charac


['\ufeff',
 "Project Gutenberg's The Adventures of Sherlock Holmes, by Arthur Conan Doyle",
 '',
 'This eBook is for the use of anyone anywhere at no cost and with',
 'almost no restrictions whatsoever.  You may copy it, give it away or',
 're-use it under the terms of the Project Gutenberg License included',
 'with this eBook or online at www.gutenberg.net',
 '',
 '',
 'Title: The Adventures of Sherlock Holmes']

In [4]:
#giving index to every word (tokenize)
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer


In [5]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(data)

In [6]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'a': 5,
 'i': 6,
 '”': 7,
 'in': 8,
 'that': 9,
 'it': 10,
 'he': 11,
 'was': 12,
 'you': 13,
 'his': 14,
 'is': 15,
 'my': 16,
 'have': 17,
 'with': 18,
 'as': 19,
 'had': 20,
 'at': 21,
 'which': 22,
 'for': 23,
 'be': 24,
 'not': 25,
 'me': 26,
 'but': 27,
 'from': 28,
 'we': 29,
 'this': 30,
 'said': 31,
 'upon': 32,
 'there': 33,
 'holmes': 34,
 'him': 35,
 'so': 36,
 'her': 37,
 'she': 38,
 'all': 39,
 '’': 40,
 'been': 41,
 'your': 42,
 'on': 43,
 'very': 44,
 'by': 45,
 'one': 46,
 'are': 47,
 '“i': 48,
 'were': 49,
 'an': 50,
 'no': 51,
 'would': 52,
 'out': 53,
 'what': 54,
 'then': 55,
 'up': 56,
 'when': 57,
 'man': 58,
 'could': 59,
 'has': 60,
 'do': 61,
 'into': 62,
 'or': 63,
 'little': 64,
 'will': 65,
 'who': 66,
 'mr': 67,
 'if': 68,
 'some': 69,
 'down': 70,
 'see': 71,
 'now': 72,
 'our': 73,
 'should': 74,
 'may': 75,
 'am': 76,
 'us': 77,
 'over': 78,
 'they': 79,
 'can': 80,
 'more': 81,
 'think': 82,
 'about': 83,
 'mu

In [7]:
sequences = tokenizer.texts_to_sequences(data)
sequences= [seq for seq in sequences if len(seq)>0]
sequences

[[4789],
 [145, 4790, 1, 1020, 4, 128, 34, 45, 611, 2235, 2236],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237, 21, 51, 1676, 2, 18],
 [572, 51, 3398, 3399, 13, 75, 817, 10, 213, 10, 124, 63],
 [2238, 275, 10, 262, 1, 480, 4, 1, 145, 130, 655, 2239],
 [18, 30, 1021, 63, 2240, 21, 1093, 130, 3400],
 [2666, 1, 1020, 4, 128, 34],
 [4791, 611, 2235, 2236],
 [4792, 1022, 4793, 4794, 4795, 1021, 2241],
 [139, 3401, 75, 3402, 4796],
 [3403, 1094],
 [573, 243, 4797, 4798, 1469],
 [722, 4, 30, 145, 130, 1021, 1, 1020, 4, 128, 34],
 [1928, 45, 50, 3404, 145, 130, 2667, 2, 3405, 3406],
 [1677],
 [1, 1020, 4, 128, 34],
 [45, 611, 2235, 2236],
 [1929],
 [6, 5, 885, 8, 940],
 [2668, 1, 248, 481, 691],
 [2669, 5, 113, 4, 2242],
 [3407, 1, 774, 1470, 522],
 [3408, 1, 312, 1023, 941],
 [3409, 1, 58, 18, 1, 1095, 942],
 [3410, 1, 612, 4, 1, 448, 1471],
 [3411, 1, 612, 4, 1, 1930, 886],
 [3412, 1, 612, 4, 1, 3413, 692],
 [3414, 1, 612, 4, 1, 818, 1340],
 [3415, 1, 612, 4, 1, 2243, 406],
 [3416, 1, 612, 4, 1, 

In [8]:
#making dataset
input_sequences = []
for sequence in sequences:
  # print(len(sequence))

  for i in range(1,len(sequence)):
      input_sequences.append(sequence[:i+1])



In [9]:
input_sequences

[[145, 4790],
 [145, 4790, 1],
 [145, 4790, 1, 1020],
 [145, 4790, 1, 1020, 4],
 [145, 4790, 1, 1020, 4, 128],
 [145, 4790, 1, 1020, 4, 128, 34],
 [145, 4790, 1, 1020, 4, 128, 34, 45],
 [145, 4790, 1, 1020, 4, 128, 34, 45, 611],
 [145, 4790, 1, 1020, 4, 128, 34, 45, 611, 2235],
 [145, 4790, 1, 1020, 4, 128, 34, 45, 611, 2235, 2236],
 [30, 1021],
 [30, 1021, 15],
 [30, 1021, 15, 23],
 [30, 1021, 15, 23, 1],
 [30, 1021, 15, 23, 1, 275],
 [30, 1021, 15, 23, 1, 275, 4],
 [30, 1021, 15, 23, 1, 275, 4, 394],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237, 21],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237, 21, 51],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237, 21, 51, 1676],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237, 21, 51, 1676, 2],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237, 21, 51, 1676, 2, 18],
 [572, 51],
 [572, 51, 3398],
 [572, 51, 3398, 3399],
 [572, 51, 3398, 3399, 13],
 [572, 51, 3398, 3399, 13, 75],
 [572, 51, 3398, 3399, 13, 75, 817],
 [572, 51, 3398, 33

In [10]:
#padding, finding max length
max_len = max([len(x) for x in input_sequences])
max_len

20

In [11]:
#padding
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding="pre")
padded_input_sequences

#pre padding cuz itll be recent better for LSTM to remember

array([[   0,    0,    0, ...,    0,  145, 4790],
       [   0,    0,    0, ...,  145, 4790,    1],
       [   0,    0,    0, ..., 4790,    1, 1020],
       ...,
       [   0,    0,    0, ...,    3,  360,   83],
       [   0,    0,    0, ...,  360,   83,  358],
       [   0,    0,    0, ...,   83,  358, 1673]], dtype=int32)

In [12]:
#defining X and Y
X = padded_input_sequences[:,:-1] #remove last 1 from each
X

array([[   0,    0,    0, ...,    0,    0,  145],
       [   0,    0,    0, ...,    0,  145, 4790],
       [   0,    0,    0, ...,  145, 4790,    1],
       ...,
       [   0,    0,    0, ..., 8931,    3,  360],
       [   0,    0,    0, ...,    3,  360,   83],
       [   0,    0,    0, ...,  360,   83,  358]], dtype=int32)

In [14]:
Y = padded_input_sequences[:,-1] #last 1 from each
Y

array([4790,    1, 1020, ...,   83,  358, 1673], dtype=int32)

In [13]:
print(X.shape)

(101619, 19)


In [19]:
Y.shape

(101619,)

In [18]:
#total words
len(tokenizer.word_index)+1
#why +1 cuz our words start from index 1 but OHE start from index 0
#tokenizer starts from 1 to 107

8932

In [19]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'a': 5,
 'i': 6,
 '”': 7,
 'in': 8,
 'that': 9,
 'it': 10,
 'he': 11,
 'was': 12,
 'you': 13,
 'his': 14,
 'is': 15,
 'my': 16,
 'have': 17,
 'with': 18,
 'as': 19,
 'had': 20,
 'at': 21,
 'which': 22,
 'for': 23,
 'be': 24,
 'not': 25,
 'me': 26,
 'but': 27,
 'from': 28,
 'we': 29,
 'this': 30,
 'said': 31,
 'upon': 32,
 'there': 33,
 'holmes': 34,
 'him': 35,
 'so': 36,
 'her': 37,
 'she': 38,
 'all': 39,
 '’': 40,
 'been': 41,
 'your': 42,
 'on': 43,
 'very': 44,
 'by': 45,
 'one': 46,
 'are': 47,
 '“i': 48,
 'were': 49,
 'an': 50,
 'no': 51,
 'would': 52,
 'out': 53,
 'what': 54,
 'then': 55,
 'up': 56,
 'when': 57,
 'man': 58,
 'could': 59,
 'has': 60,
 'do': 61,
 'into': 62,
 'or': 63,
 'little': 64,
 'will': 65,
 'who': 66,
 'mr': 67,
 'if': 68,
 'some': 69,
 'down': 70,
 'see': 71,
 'now': 72,
 'our': 73,
 'should': 74,
 'may': 75,
 'am': 76,
 'us': 77,
 'over': 78,
 'they': 79,
 'can': 80,
 'more': 81,
 'think': 82,
 'about': 83,
 'mu

In [25]:
#one hot encoding the output (considering this a multi classification problem)
from tensorflow.keras.utils import to_categorical
vocab_size = len(tokenizer.word_index) +1
print(vocab_size) # 8932
y = to_categorical(Y, num_classes=vocab_size)


8932


In [26]:
y.shape

(101619, 8932)

In [27]:
len(X[1])

19

In [28]:
#building model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [29]:
model = Sequential()
model.add(Embedding(vocab_size,150,input_length=19))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation="softmax"))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [31]:
model.fit(X,y, epochs=100)

Epoch 1/100
3176/3176 ━━━━━━━━━━━━━━━━━━━━ 31s 8ms/step - accuracy: 0.0541 - loss: 6.6708
Epoch 2/100
3176/3176 ━━━━━━━━━━━━━━━━━━━━ 25s 8ms/step - accuracy: 0.0969 - loss: 5.8133
Epoch 3/100
3176/3176 ━━━━━━━━━━━━━━━━━━━━ 24s 8ms/step - accuracy: 0.1316 - loss: 5.4247
Epoch 4/100
3176/3176 ━━━━━━━━━━━━━━━━━━━━ 24s 8ms/step - accuracy: 0.1555 - loss: 5.1153
Epoch 5/100
3176/3176 ━━━━━━━━━━━━━━━━━━━━ 41s 8ms/step - accuracy: 0.1703 - loss: 4.8905
Epoch 6/100
3176/3176 ━━━━━━━━━━━━━━━━━━━━ 24s 8ms/step - accuracy: 0.1843 - loss: 4.6733
Epoch 7/100
3176/3176 ━━━━━━━━━━━━━━━━━━━━ 24s 8ms/step - accuracy: 0.1944 - loss: 4.5012
Epoch 8/100
3176/3176 ━━━━━━━━━━━━━━━━━━━━ 41s 8ms/step - accuracy: 0.2104 - loss: 4.3258
Epoch 9/100
3176/3176 ━━━━━━━━━━━━━━━━━━━━ 24s 8ms/step - accuracy: 0.2245 - loss: 4.1779
Epoch 10/100
3176/3176 ━━━━━━━━━━━━━━━━━━━━ 24s 8ms/step - accuracy: 0.2369 - loss: 4.0073
Epoch 11/100
3176/3176 ━━━━━━━━━━━━━━━━━━━━ 25s 8ms/step - accuracy: 0.2500 - loss: 3.8810
Epoch 12

In [29]:
# Training: text_on_sequence converts already indexed words into their original numeric sequence as in the sentence
# Prediction: converts new words into their original training indices (OOV words → 0) for model input


In [32]:
import numpy as np
text = input("Enter the word: ")
num_words = int(input("Enter the Number of words you want: "))


for i in range(num_words):

  #tokenize
  test_word = tokenizer.texts_to_sequences([text])[0]
  #padd
  pa = pad_sequences([test_word], maxlen=17, padding="pre")


  #predict
  outout = model.predict(pa)
  outind = np.argmax(outout)
  outind

  output = tokenizer.index_word[outind]

  #next 5 words
  text = text + " " + output
print(text)

Enter the word: Project
Enter the Number of words you want: 10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Project gutenberg tm ebooks are often created from violet reopening by
